name: dpvo
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.10
  - pytorch=2.3.1
  - pytorch-scatter=2.1.2
  - pytorch-cuda=12.1
  - torchvision=0.18
  - pip:
    - tensorboard
    - numba
    - tqdm
    - einops
    - pypose
    - kornia
    - numpy==1.26.4
    - plyfile
    - evo
    - opencv-python
    - yacs

# pip install torch==2.8.0 torchvision==0.23.0 torchaudio==2.8.0 --index-url https://download.pytorch.org/whl/cu128
# pip install torch-scatter -f https://data.pyg.org/whl/torch-2.8.0+cu128.html
# pip install tensorboard numba tqdm einops pypose kornia numpy plyfile evo opencv-python yacs

# git clone --recursive https://github.com/princeton-vl/lietorch.git
# cd lietorch

# python3 -m venv .venv
# source .venv/bin/activate

# # install requirements
# pip install torch torchvision torchaudio wheel

# # optional: specify GPU architectures
# export TORCH_CUDA_ARCH_LIST="7.5;8.6;8.9;9.0"

# # install lietorch
# pip install --no-build-isolation .


# pip install --no-build-isolation .

